# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: sqlmesh
  version: 0.236.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sqlmesh-${{ version }}.tar.gz
  sha256: 50e49dab5d1e669f47a319263f4d68dce620949a1fc1f15beece8e6e4f006fa2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sqlmesh = sqlmesh.cli.main:cli
      - sqlmesh_cicd = sqlmesh.cicd.bot:bot

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - pip
  run:
    - humanize
    - python-dotenv
    - python >=${{ python_min }}
    - click
    - croniter
    - python-duckdb >=0.10.0,!=0.10.3
    - dateparser <=1.2.1
    - hyperscript >=0.1.0
    - importlib-metadata
    - ipywidgets
    - jinja2
    - packaging
    - pandas <3.0.0
    - pydantic >=2.0.0
    - requests
    - rich
    - ruamel.yaml
    - sqlglot >=30.8.0,<30.9.dev0
    - tenacity
    - time-machine
    - json_stream
tests:
  - python:
      imports:
        - sqlmesh
        - web
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - sqlmesh --help
      - sqlmesh_cicd --help

about:
  homepage: https://github.com/TobikoData/sqlmesh
  summary: Efficient data transformation and modeling framework that is backwards compatible with dbt.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - fhoehle
